### ISSUE TITLE
Elements Panel V2

### ISSUE THREAD

**Issue by jasonLaster** [RecordReplay/devtools#1227]
**Description**

The V1 was a just barely works version. With V2, we're focusing on architecting the panel to 

1. work reliably
2. be maintainable

**This involves**

* migrating to react and removing old code
* removing functionality we do not use
* making sure the core functionality works as expected

**Todolist**
- [x] Render inspector sidebar panels in react tree #1210
- [x] Inspector keyboard shortcuts #1062
- [x] Fix the breadcrumbs scroll buttons #338
- [x] Cannot read property 'getMatchedSelectors' of undefined #1097
- [ ] persist markup expand state across pauses #1116
