### ISSUE TITLE
"Playability" UX tweaks

### ISSUE THREAD

**Issue by jonbell-lot23** [RecordReplay/devtools#1237]
We've discussed each of these issues before, but I'd like to put them all in one place:

- [x] New replays should start at the beginning, not the end #1268
- [x] Let's try auto-playing it on load -- that helps us get around the black screen issue #1269
- [x] Please rotate the replay arrow in the player to point forwards. Right now it's backwards. #1270
- [x] Scrubbing timeline should update the playback region, and we should drop the thumbnail #1271
- [ ] Clicking in the playback region should pause and play, like YouTube

**Comment by jonbell-lot23** [comment]
I've summarised a bunch of thinking here: https://www.notion.so/replayio/Playability-Rationale-Doc-781baff5abda475589ebdc8eb499ca27

**Comment by jaril** [comment]
Fixed in #1288
