### ISSUE TITLE
[UX] Design cleanup (Christmas bundle)

### ISSUE THREAD

**Issue by jonbell-lot23** [RecordReplay/devtools#1301]
In the Figma doc, look for the page called "Exploration - Christmas UX." I've been making a bunch of tweaks to go along with the Playability bundle. Here they are, let me know if you have questions or comments!

- [x] A: Mousing over the timeline should color the line, the way YouTube does it. #1327
- [x] B: Play button should be bigger #1329
- [x] C: Add 10 pixels to the bottom of the timeline #1329
- [x] D: “Play” should be “Viewer” and “Debug” should be “Debugger” #1330

![Diana](https://user-images.githubusercontent.com/9154902/102732367-63504c80-439f-11eb-9eb7-5bc9aac04520.png)

- [x] H: Remove icons from the toolbox #1331
- [ ] I. Hovering over playback region should light up the play button, and clicking should play/pause like Netflix/YouTube
- [x] J: Put back the button for collapsing the Sources/Outline panel #1333

![Ellen](https://user-images.githubusercontent.com/9154902/102732550-dce83a80-439f-11eb-900d-717cb9956ad0.png)

**Comment by jaril** [comment]
I have PRs open for everything but one (I) which I'm moving to a separate issue.

**Comment by jaril** [comment]
Not sure why I reopened this, this is all finished.
