### ISSUE TITLE
Library project

### ISSUE THREAD

**Issue by jasonLaster** [RecordReplay/devtools#1311]
- [ ] Grouping: opened, created, domain #1414
- [ ] Dim out broken replays (maybe #1414)
- [ ] See recent recordings (maybe #1414)
- [ ] Favorite recordings
- [ ] scrolling in the list, domains
- [ ] shift-click to select up https://github.com/RecordReplay/devtools/issues/1149
- [ ] Support team workspaces #1010

**Comment by jonbell-lot23** [comment]
@jasonLaster is "Accounts" the right name for this? I'd think of this as the Replay Library or the View Page.

**Comment by jasonLaster** [comment]
@jonbell-lot23 is this still the best project for library tasks?

**Comment by jonbell-lot23** [comment]
Yup there's another one but let's close it out and use this.

**Comment by jonbell-lot23** [comment]
A lot has changed since we opened this issue, and we are tracking library changes as part of Ready Player Two.

I propose we close this for now, but of course some of these items will come back later on as we work through our priority list.
