### ISSUE TITLE
[UX] Project Pohutakawa

### ISSUE THREAD

**Issue by jonbell-lot23** [RecordReplay/devtools#1413]
It's good to bundle UX changes into a cohesive "release" to help things feel like part of a unified whole rather than floating features. To that end, I'm starting up Project Pohutukawa.  (Pronounced poe-hutu-kawa, it's a tree in New Zealand that [blooms at Christmas](https://www.google.com/search?q=pohutukawa&source=lnms&tbm=isch&sa=X&ved=2ahUKEwiQr9nE6fPtAhXRbCsKHdeuCV4Q_AUoAXoECBMQAw&biw=811&bih=789&dpr=2))

This release is laser-focused on building out features that address the issues we saw in [Round #3: Beta List](https://www.notion.so/Round-3-Beta-List-c0d686604960497c83c51188df8365e1) user research. That means the issues are mostly oriented around Perception and Onboarding improvements.

[Here's the master design doc for Project Pohutakawa](https://www.notion.so/replayio/Project-Pohutukawa-c58f3c08a6ee45449e7a15bfa00fd4f6)

- [ ] Events Filter + Transcript (#1308)
- [ ] Loading flow v2 (#1365)
- [ ] Add loading progress bars to panels (#1410)
   - [ ] Make empty breakpoint panel #1402 
- [ ] Add loading progress bars to panels (#1372)
- [ ] Viewer controls
   - [ ] Add right-click to Playback region #1405
   - [ ] Add duration to timeline #1408 
- [ ] Comments everywhere v1 (#1309)
   - [ ] Playback region (Dupe: #1405)
   - [ ] Event
   - [ ] Breakpoint
   - [ ] Console
- [ ] Replay Library (aka Accounts) (#1311)
   - [ ] Accounts page design update (#1391)
   - [ ] Group by created/opened
   - [ ] Show recent recordings

**Comment by jasonLaster** [comment]
i'm going to close a bunch of these for now to keep the issue list low. easy to re-open when we're ready

**Comment by jonbell-lot23** [comment]
I'm closing this broader project to make a more focused one. Please see #1531.
