### ISSUE TITLE
[UX] Project 10 WAU (Weekly Active Users)

### ISSUE THREAD

**Issue by jonbell-lot23** [RecordReplay/devtools#1531]
Project Pohutakawa #1413 was a larger project that we're trimming down to be more focused on perceived performance features. The end goal is to make features that will help us reach 10 Weekly Active Users. These features are:

**UX TWEAKS**

- [x] Timeline shouldn't resize on hover (https://github.com/RecordReplay/devtools/issues/1537)
- [x] 1:1 relationship between events log and timeline (https://github.com/RecordReplay/devtools/issues/1538)
- [x] Devtools: simplify events log (https://github.com/RecordReplay/devtools/issues/1539)

**PERCEIVED PERFORMANCE**

- [x]  Loading flow v2 ([#1365](https://github.com/RecordReplay/devtools/issues/1365))
- [x]  Add loading progress bars to panels ([#1410](https://github.com/RecordReplay/devtools/issues/1410))

**METRICS/MOTIVATION**
- [x] Show Weekly Active Users in the admin dashboard ([#1533](https://github.com/RecordReplay/devtools/issues/1533))

**ONBOARDING/DOCUMENTATION**

- [ ]  Onboarding documentation
- [ ]  Make empty breakpoint panel #1402
- [ ]  Ellen Comments

**Comment by jonbell-lot23** [comment]
The main parts of this issue have gone live.
