### ISSUE TITLE
[UX] February 8 visual bugs

### ISSUE THREAD

**Issue by jonbell-lot23** [RecordReplay/devtools#1733]
A project for tracking the visual bugs I'm seeing on production:

- [x] Left Wing UI polish #1734
- [ ] Playhead should jump to first comment #1670
- [ ] If no comment, playhead should jump to 2 seconds in #1671

**Comment by jasonLaster** [comment]
closing as we're close to doing #1670 and #16711
