### ISSUE TITLE
[UX] GUTE-1

### ISSUE THREAD

**Issue by jonbell-lot23** [RecordReplay/devtools#1793]
This is a project issue for tracking our first round of "Grand Unified Theory of Everything" items. Here's the list in priority order:

- [x] Devtools/Comments pane should only show events when attached to a comment #1791
- [x] [UX] Devtools timeline should be completely blank by default #1792
- [x] This means Breakpoints get a redesign! (Pending design)
- [ ] Add more events to Viewer/Transcript #1790

**Comment by jasonLaster** [comment]
Going to suggest two more additions:

5. comments should hang off of events
6. timestamps should appear as timeline tooltips



----

### comments should hang off of events

old / new

![Frame 2](https://user-images.githubusercontent.com/254562/107797090-6583b700-6d0f-11eb-8069-e2ec5fbaa6e1.png)


### timestamps should appear as timeline tooltips

We just need to show the timestamp tooltip when the user hovers on an event!

![Frame 3](https://user-images.githubusercontent.com/254562/107797495-daef8780-6d0f-11eb-871b-bf3787005220.png)

**Comment by jonbell-lot23** [comment]
I think we can close this because the final item in GUTE-1 (showing new events like drag & drop) are a non-Jaril thing.

**Comment by jasonLaster** [comment]
We can add more events separately
