### ISSUE TITLE
Project Focus

### ISSUE THREAD

**Issue by jasonLaster** [RecordReplay/devtools#1905]
### Recording

Status of design: (Which does not include Jaril's work putting the designs into code)

- [ ] add recording timer with a cap at 1 minute #1939
- [ ] add a recording size count down with a cap of 50mb #1939
- [ ] add clearer error messages for web apis #2026 

### Replaying

- [x] disable elements panel + node picker #1938
- [x] prevent logpoint evaluations when 100+ points #2027 
- [x] don't show logpoints in console when 250+ points #2028 
- [x] limit event types (mouse only?)

**Comment by jonbell-lot23** [comment]
@jaril Some of these issues are on me (such as the 1 minute limitation work) but others are in the code. So some of these can be done now.

**Comment by jonbell-lot23** [comment]
Closing this out. Note that the 250+ breakpoint design is at a very low fidelity right now. I'll address the visual treatment as part of a broader Figma/design system update.
