### ISSUE TITLE
Waitlist/invites project

### ISSUE THREAD

**Issue by jasonLaster** [RecordReplay/devtools#2200]
[Edited original description to track these three tasks]

- [x] [Welcome page shouldn't have download links anymore](https://github.com/RecordReplay/devtools/issues/2203)
- [ ] [Add the ability to invite people on your domain](https://github.com/RecordReplay/devtools/issues/2204)
- [x] [Add the ability to invite anyone to Replay](https://github.com/RecordReplay/devtools/issues/2205)
- [x] [Add a download button to the logged in ui](https://github.com/RecordReplay/devtools/issues/2210)

**Comment by jonbell-lot23** [comment]
I’m not concerned about people knowing where they are in the queue. We’re not inviting people sequentially.

I’m not concerned about people sharing the URL and a flood of users coming. It’s a small risk I’m ok with in order to ruthlessly prioritise making the boat go faster.

On the other hand, I am very interested in tracking people who have have been given a download link, and synchronising that across Airtable, Intercom, and even lighting it up in the UI.

—

So I’d propose prioritising there. I want a great Team Spirit Health Dashboard, which all starts with knowing what percentage of invited users are logging in, and how frequently. Then we tie that activity to people on their team/in their org.
