### ISSUE TITLE
Project Be More Like YouTube

### ISSUE THREAD

**Issue by jonbell-lot23** [RecordReplay/devtools#2289]
There are three components we need to get right:

- [x] It should be possible to drag the playhead forward and back (https://github.com/RecordReplay/devtools/issues/2236)
- [x] Buffering should show in the progress bar itself (#2350)
- [ ] The playhead shouldn't appear until you hover over the timeline (#2256)

(Stay tuned for more details, this is a placeholder for now)

**Comment by jonbell-lot23** [comment]
@jasonLaster we talked about making a ticket for this yesterday. @hbenl copying you because your name came up for these changes.

**Comment by jonbell-lot23** [comment]
Hello! Here's a quick movie explaining each of these fixes and how to make them more like YouTube's UX:
https://share.descript.com/view/UAODGMZ962r

**Comment by jonbell-lot23** [comment]
Just added #2350 to provide specifics to the YouTube-style interface
