### ISSUE TITLE
RPT-3 (Ready Player Two, stage 3)

### ISSUE THREAD

**Issue by jonbell-lot23** [RecordReplay/devtools#2352]
The next batch of issues standing in the way of getting more people onboarding their coworkers.

**--> (This list is not in priority order yet, it's currently in journey order) <--**

**Download of the app:**

- [x]  Fix our app icon ([#338](https://github.com/RecordReplay/gecko-dev/issues/338))
- [x]  Background image on app icon ([#337](https://github.com/RecordReplay/gecko-dev/issues/337))
- [ ]  Download instructions ([#2355](https://github.com/RecordReplay/devtools/issues/2355))

**First load**

- [x]  Where did our welcome screen go? ([#2234](https://github.com/RecordReplay/devtools/pull/2234) but it's stalled)
- [ ]  FF import experience is confusing (addressed by download instructions and welcome screen?)
- [ ]  Clicking record from Replay should ask if you're sure (low priority)
- [ ]  Clicking record should ask if it's ok to reload the page ([#339](https://github.com/RecordReplay/gecko-dev/issues/339))

**Experience**

- [x]  The loading screen flashes black and it looks ugly ([#2356](https://github.com/RecordReplay/devtools/issues/2356))
- [x]  [UX] Great warning screens (for starters, the "you don't have access yet" screen needs to be great) ([#2357](https://github.com/RecordReplay/devtools/issues/2357))
- [x] Project Be More Like YouTube ([#2289](https://github.com/RecordReplay/devtools/issues/2289))

**Comments**

- [x] Add comments to a line of code ([#2358](https://github.com/RecordReplay/devtools/issues/2358))
- [x] More broadly, we're moving our comments to usebubbles.com style UI (stay tuned for this)

**Comment by jonbell-lot23** [comment]
Closing this out because the remaining items are mostly gecko-dev
