### ISSUE TITLE
RPT-4

### ISSUE THREAD

**Issue by jonbell-lot23** [RecordReplay/devtools#2499]
This is now in buckets and in order based on chats with Jaril

## Highest priority

- [x] Team dropdown defaults to "—-" but should be "My Library" (we might rename it later!)
- [x] Should highlight the left-hand side when you click on a comment to tie it together
- [x] The upload screen should not show alongside the video. It should be its own screen. #2532

## Other (shovel ready -- Jon to revise once we have the basics)

- [x] "Make publicly available" copy is confusing people
- [x]  Our reload screen is too "heavy" (as in sad) as Jason says
- [x] Sign in modal dialog is way too tall and not designed (align to other modals)
- [x] Should be able to transfer from each item in the library (behind three dots) (fixed in #2567)
- [x] Sign in button isn't the right size/shape when logged out (top right)
- [x] Clicking on a line of code in transcript should go to that line of code
- [x] Default library state is confusing. Should remove two default videos and show text + illustration. #2542
- [x] Add an All Replays view #2534

(I carved off these other items into this ticket for design to work on: https://github.com/RecordReplay/devtools/issues/2544)

**Comment by jaril** [comment]
Split off some separate issues:

https://github.com/RecordReplay/devtools/issues/2534
https://github.com/RecordReplay/devtools/issues/2533
https://github.com/RecordReplay/devtools/issues/2532

**Comment by jonbell-lot23** [comment]
Just moved the needs-design issues into a separate issue so design doesn't block this issue from getting closed out: #2544
