### ISSUE TITLE
[UX] RPT-4.5

### ISSUE THREAD

**Issue by jonbell-lot23** [RecordReplay/devtools#2544]
These are items waiting on Jon to design:

- [x]  Multiple comments at the same time #2533
- [x]  We need an empty state for comments #2540
- [ ]  Events log (in devtools) is not great #2535
- [ ]  Events log needs to be put back into the viewer
- [ ]  People not clear how to jump forward and backward in time
- [ ]  Purple line in the console isn't clear
- [ ]  Jason's "comment without requiring a comment" candy idea
- [ ] Audit our onboarding flows (there are multiple use cases to track and make sure are great)
- [ ] Amp up our team angle

**Comment by jonbell-lot23** [comment]
Closing out this ticket to have more consistent naming
