### ISSUE TITLE
Jon's notepad (Features)

### ISSUE THREAD

**Issue by jonbell-lot23** [RecordReplay/devtools#2562]
- [ ] Add to timeline via right click https://github.com/RecordReplay/devtools/issues/2614
- [ ] Add comment on console message without requiring anything other than a flag https://github.com/RecordReplay/devtools/issues/2615
- [ ] Kids version of events - mouse, key, nothing else https://github.com/RecordReplay/devtools/issues/2616
- [ ] Rad new header https://github.com/RecordReplay/devtools/issues/2579

**Comment by jasonLaster** [comment]
@jonbell-lot23 this feels like it should be tracked in ops

**Comment by jonbell-lot23** [comment]
Split these out into their own issues. (All devtools, not ops)
