### ISSUE TITLE
Pride & Craft: 1

### ISSUE THREAD

**Issue by jonbell-lot23** [RecordReplay/devtools#2564]
This is a project for tracking fit and finish items. We'll be using Pride & Craft projects on an ongoing basis. They're for revisions to currently existing features, not a place to put brand new ones. We'll limit each batch to 10.

- [x] Commenting disabled needs new text
- [x] Blue outline on the toggle looks awkward
- [x] We're using the wrong blue on the upload screen
- [x] Header broke on the upload screen (Should be H2, but it's just normal text now)
- [x] Empty state for comments https://github.com/RecordReplay/devtools/issues/254
- [x] Give the search box a border #2603
- [x] Upload title is missing a border too  #2603
- [x] The email should have the link itself, not just "click here"
- [x] Explain that we're using Google sign in, don't just say "Sign into Replay"
- [x] All Time dropdown should be wider

**Comment by jonbell-lot23** [comment]
Exciting! Our first batch of Pride & Craft items have been closed out!

**Comment by jonbell-lot23** [comment]
Here's Pride & Craft #2: https://github.com/RecordReplay/devtools/issues/2593
