### ISSUE TITLE
[UX] Pride & Craft: 2

### ISSUE THREAD

**Issue by jonbell-lot23** [RecordReplay/devtools#2593]
- [x]  Resizing panels can create weird overflows (perhaps we should not resize the left pane) (moved to #2535)
- [x]  Comments default text should have different text if you're logged out (save for @jonbell-lot23)
- [x] New comment is adding to line of code rather than x,y value #2636
- [x]  Clicking the title should swap out the title nicely. Right now it jumps to the side and has no border on click. **(fixed by #2638)**
- [x] Don't allow someone to navigate away from the upload screen without a prompt **(fixed by #2629)**
- [x] Update comment marker look and feel (ebbing, centering, sizing)
- [x] Comments appear above modals (errors, quick open) **(fixed by #2632)**
- [x] Dropdowns should save state **(fixed by #2631)**
- [x] Team should never be called "---" **(fixed by #2630)**

**Comment by jonbell-lot23** [comment]
I did my item. PR here: https://github.com/RecordReplay/devtools/pull/2649

**Comment by jonbell-lot23** [comment]
Good night, sweet prince. We did a lot of good work on this issue.
