### ISSUE TITLE
Startup: Creating a replay

### ISSUE THREAD

**Issue by jasonLaster** [RecordReplay/devtools#2626]
**Description:**

We consistently hear that the primary reason folks don't use Replay more is the friction associated with startup times. 

### Starting a replay

- [x] The record button should turn red immediately
- [X] The record button should show a spinner while starting RecordReplay/gecko-dev#398

**Tasks**

- [X] Record button turns red immediately #369 

### Saving a replay

**Requirements**

- [x] The record button should turn blue immediately
- [x] The record button should show a spinner while saving RecordReplay/gecko-dev#398

**Tasks**

- [X] Record button turns blue immediately #369
- [X] Replay tab is immediately created to the right 
- [x] Immediate upload screen (with blue background)
- [ ] Add an Upload screen error  https://github.com/RecordReplay/gecko-dev/issues/368  (also see https://github.com/RecordReplay/devtools/issues/2655)

### Upload Screen

**Requirements**

- [x] The upload screen immediately
- [x] The upload screen should stream in data when it is available
- [x] The upload screen should show if there was an error
- [ ] If the user saves the replay before the replay is done uploading, they should see progress bars

**Tasks**

- [x] Uploading screen shows upload progress (https://github.com/RecordReplay/devtools/issues/2655)
- [x] Uploading screen error (https://github.com/RecordReplay/devtools/issues/2655)
- [ ] Show uploading progressbars https://github.com/RecordReplay/devtools/issues/2696
