### ISSUE TITLE
Onboarding: Inviting and Sharing

### ISSUE THREAD

**Issue by jonbell-lot23** [RecordReplay/devtools#2669]
- [x] Adding a new collaborator should send an invitation [#2037](https://github.com/RecordReplay/backend/issues/2037)
- [x] When inviting/adding a user, we need a spinner and error messages (#2670)
- [x] Accepting an invite to a team should take me to that team (#2484)
- [x] Clicking URL field should copy to clipboard (#2293)
- [x] [UX] Invalid recording ID should have a login button (#2664)
- [x] When sharing or inviting, the list of collaborators should be in reverse-chronological order so the newest person is always on top (#2719)
- [x] Adding a collaborator should send them an email https://github.com/RecordReplay/devtools/issues/2710
