### ISSUE TITLE
Teams can't be deleted

### ISSUE THREAD

**Issue by jonbell-lot23** [RecordReplay/devtools#2685]
Add the ability to delete a team is pretty straight-forward (I assume) but of course the UX/flow is harder. Here's my proposal:

* This should be in the "gear" menu
* Delete this team -> Modal dialog explaining that this is a big deal and not undoable
* After they confirm, we ask them what team they'd like to move the Replays into (if there are Replays)
* Confirmation div: "The team [name] has been deleted and [x] replays have been moved to [team.]"

Tracking items here:

- [x] Add deleteWorkspace to the graphql api [#2399](https://github.com/RecordReplay/backend/pull/2399)
- [x] Add UI for deleting a team #2904

Follow-up:

- Need to discuss what happens to the following when a team is deleted:
  - Replays (delete? move to owner's personal library? don't move back to owner's personal library?)
  - API keys (delete? don't delete?)
  - Sourcemaps (delete? don't delete?)

**Comment by jonbell-lot23** [comment]
Now that we're getting more real users and real teams, this functionality is feeling more primary. Re-upping.

**Comment by jaril** [comment]
Splitting this into a few items:
- [ ] Add deleteWorkspace to the graphql api [#2399](https://github.com/RecordReplay/backend/pull/2399)
- [ ] Add a button for deleting a team in the team settings modal
