### ISSUE TITLE
Onboarding: Teams

### ISSUE THREAD

**Issue by jonbell-lot23** [RecordReplay/devtools#2706]
- [x] Add support for onboarding by domain https://github.com/RecordReplay/devtools/issues/2720
- [x] Add a TeamFlow style team invitation step (#2690)
- [x] [UX] Team setup should include invite screen (#2648)
- [ ] Whitelist domain such that users with matching domains for a team are automatically invited when they log in, even without an invitation codde.
