### ISSUE TITLE
Startup: viewing a replay

### ISSUE THREAD

**Issue by jasonLaster** [RecordReplay/devtools#2733]
**Description**

### Viewer

**Requirements**
- [ ] The viewer should be available after the session is created
- [ ] Users should be able to view paint contents while the video is being generated
- [ ] The video should be available when basic indexing completes

**Tasks**
- [x] The video should be available as soon as possible https://github.com/RecordReplay/backend/issues/2044
- [x] The cursor events should be available as soon as possible https://github.com/RecordReplay/backend/issues/2044
- [x] Comments source snippet should be stored in the db #2452
- [x] Comment syntax highlighting doesn't work before opening DevTools #2651

### DevTools

**Requirements**
- [ ] The devtools should be available after the session is created
- [ ] The devtools should show a global execution progress indicator as well as JIT progress indicators 
- [ ] Source content should be available from basic indexing
- [ ] Breakpoint positions should be available from basic indexing
- [ ] Console logs and Event handlers should be available from basic indexing

**Tasks**
- [x] Show breakpoint positions as soon as possible https://github.com/RecordReplay/backend/issues/2043
- [x] The breakpoint hits tooltip should show we're indexing #2703
- [x] Show a global indexing progress ui https://github.com/RecordReplay/devtools/issues/2659

## 3. Miscellaneous

- [x] Split the bundle by library, viewer, and devtools https://github.com/RecordReplay/devtools/issues/2644
