### ISSUE TITLE
Add support for invite links

### ISSUE THREAD

**Issue by jaril** [RecordReplay/devtools#2802]
Teams should be able to create a unique link to share with their teammates. If a teammate registers for Replay using that link, they should see an invitation for the team as soon as they log in. Or even better, they should just become a part of that team immediately.

Doing this in a few stages:
- [x] Keep track of who created a workspace. ([#2342](https://github.com/RecordReplay/backend/pull/2342)).
- [x] Create a `invitation_code` field in the workspace table. ([#2350](https://github.com/RecordReplay/backend/pull/2350))
- [x] Handle the invitation code when a user first signs up to invite them to the corresponding team. ([#2362](https://github.com/RecordReplay/backend/pull/2362))
- [x] Show the shareable link with the invitation code in the team leader onboarding flow. (#2865)
- [x] Show the shareable link with the invitation code in the create new team flow. (#2865)

Follow-ups:
- Show the shareable link in the team settings. (#2871)
- Add a checkbox for limiting access to a team invitation link (#2872)
- Add support for expiring codes. (#2873)
