### ISSUE TITLE
Onboarding: Team invite flow

### ISSUE THREAD

**Issue by jaril** [RecordReplay/devtools#2803]
## Summary
- When a Replay employee wants somebody to use Replay, they should always invite them through the settings panel's invitations tab.
- People invited through the Replay invitations tab should be prompted to make a team and invite members as soon as they log in.
- People invited through a team invitation should be prompted to join that team as soon as they log in.
- This flow prioritizes making sure that a new user lands in the right team, over downloading the Replay browser. (Should be reversed later because it's unnatural).

## Requirements
- [x] Add the team leader flow #2804
- [x] Add a team member flow for new users who were invited as team members #2690
- [x] Allow the user the invite team members during the team leader flow #2801
- [x] Last viewed team not always the default team to land on #2800

## Motivation
- Right now, the onboarding process is disjointed.
- There's no clearly mapped way of how we get a person to from somebody we've talked to, all the way to creating a new team for their team, inviting members, and creating replays.
- Once that user does invite team members, there's also clearly mapped way of how we get that invited team member all the way to joining the team, and creating replays.
- This defines an unambiguous user onboarding flow for both of those cases.

## Who gets to use Replay
- Currently, there's no comprehensive invite system to manage who gets to sign up for Replay and who doesn't. Anyone can technically sign up for Replay if they happen to have knowledge of 1) the replay.io/view url, 2) the replay.io/welcome, or 3) the replay browser installer.
- To keep the beta user list manageable with this constraint, we separate those who've signed up for Replay as either qualified, or unqualified.
- **Qualified beta users** are people who are connected to one or more Replay employee/s. This includes people we want to test Replay, and their immediate team.
- **Unqualified beta users** are people who happen to access Replay, but is not connected to a Replay employee. In such cases, their account is "uninvited" and we limit the things they can do within Replay.
- The invite flow should manage the onboarding flow for qualified beta users.

### Team leader flow
Guides the user through creating a team, adding team members, installing Replay, and creating their first replay.

1) Replay Employee talks to a potential beta user Beta User 1.
2) Replay Employee finishes the call and sends them an invite to Replay using the settings panel.
3) Beta User 1 receives an e-mail saying that they've been invited to Replay, along with a link.
4) Beta User 1 opens the link in their existing browser and registers for Replay.
5) Beta User 1 is shown the **team leader onboarding modal**.
6) Beta User 1 creates a team (Team A), invites their team members and proceeds to open their new team library.
7) The team library is empty, so Beta User 1 is prompted to record their first Replay by first downloading the Replay Browser.
8) Beta User 1 downloads, installs, and opens the Replay Browser.
9) Beta User 1 signs in to their Replay account in the Replay Browser.
10) Beta User 1 is shown the empty Team A library, and is prompted to record their first Replay by opening a new tab, going to a website, and hitting record.

### Team member flow
Guides the user through joining a team, installing Replay, and creating their first replay.

1) Beta User 2 is messaged on Slack by Beta User 1 to notify them that they're trying out this new thing called Replay, and that Beta User 2 has been sent an invitation.
2) Beta User 2 receives an e-mail saying that they've been invited to Replay, along with a link.
3) Beta User 2 opens the link in their existing browser and registers for Replay.
4) Beta User 2 is shown the **team member onboarding modal**.
5) Beta User 2 joins the team (Team A) and proceeds to open their team library.
6) The team library may/may not have replays in it already.
7) Beta User 2 hasn't recorded any replays yet, so they're prompted to record their first Replay by first downloading the Replay browser.
8) Beta User 2 downloads, installs and opens the Replay Browser.
9) Beta user 2 signs in to their Replay account in the Replay Browser.
10) Beta User 1 is shown the empty Team A library, and is prompted to record their first Replay by opening a new tab, going to a website, and hitting record.

## Follow-up
These items should be tracked as issues and either added to the requirements on this tracking issue, or as requirements on the next/separate tracking issue.
- [x] There should be a separate "Download replay" modal (dismissable) Team leader flow step 7, and Team member flow step 7. #2848
- [x] There should be a separate "Your first replay" modal (dismissable) that is shown to users in the Replay browser if they haven't recorded their first replay. This would be shown during these steps: Team leader flow step 10, and Team member flow step 10. #2847
- [x] Add validation for the new team and team member invitation forms. #2845
- [x] Make the design.. better.
- [x] Incorporate the launch replay button #2688.

### Team leader onboarding modal

```
Welcome to Replay

We're excited to have you! Next, we'll guide you through creating your own team and inviting your team members to Replay.

[Let's get started]
```

```
Your team name

To start, what would you like your team's name to be?

// Team name input field

[Skip this step] [Next]
```

```
Your team members

Next, we need to add your team members to the X team. 

// Email address input field
// List of email addresses that have been invited

[Next]
```

```
Team setup complete

Now every time you create a Replay, it's marked private and is saved in your team's library. That means only your team members can view it.

Next, we'll help you record your first replay. We'll guide you through installing the Replay Browser, which is what you'll use to create replays.

[Ok, let's go]
```

### Team member onboarding modal

```
You're invited to join the {teamName} team

[Skip this step] [Accept the invitation]
```

**Comment by jaril** [comment]
Install step:
- Install button
- It should take you to a different flow
- Explain why it's there for
- Mac / Linux / Windows (sorry)

**Comment by jaril** [comment]
Always have a ACCEPT ME modal when there's an outstanding team invite.
