### ISSUE TITLE
Onboarding: Team invite flow follow-up

### ISSUE THREAD

**Issue by jaril** [RecordReplay/devtools#2849]
With the core of the team invite flow taken care of in #2803, this is a tracking issue for all of the follow-up items from that work.

- [x] Have a dismissable tutorial for teaching new users with no recorded replays how to record their first one #2847
- [x] Smoothen the transition between the user's browser and the Replay browser #2848
- [x] Team member and replay invitations don't validate the email inputs #2845
- [x] Handle cases where a non-authorized user uses a team invitation link #2887
- [x] The modal for team leader onboarding and new team have inconsistent add member screens #2891
