### ISSUE TITLE
Add a checkbox for limiting access to a team invitation link

### ISSUE THREAD

**Issue by jaril** [RecordReplay/devtools#2872]
Splitting this up into a few pieces, in this order:

- [x] Add domain and isDomainLimitedCode fields to the workspaces table. [#2380](
https://github.com/RecordReplay/backend/pull/2380)
- [x] Whenever a user creates a new workspace, we should use their email address's domain and add it as the `domain` value for that team. [#2380](
https://github.com/RecordReplay/backend/pull/2380)
- [x] Retroactively update each workspace record's `domain` field by using the oldest team member's email address's domain.
- [x] Make sure the `domain` field is not nullable.
- [x] Add a new mutation to the graphql api to toggle `is_domain_limited_code`. [#2384](
https://github.com/RecordReplay/backend/pull/2384)
- [x] Handle both non-limited and limited cases in the backend. [#2385](
https://github.com/RecordReplay/backend/pull/2385)
- [x] Add the new checkbox to the frontend. (#2885)
- [x] Make sure that users who use the team invitation code to register for Replay are invited [#2385](
https://github.com/RecordReplay/backend/pull/2385)

Follow-up:
- Handle cases where a non-authorized user uses a team invitation link (#2887)
- The modal for team leader onboarding and new team have inconsistent add member screens (#2891)
