### ISSUE TITLE
Improve bundling

### ISSUE THREAD

**Issue by hbenl** [RecordReplay/devtools#2906]
**Description:**
- [ ] switch between library/viewer/devtools without reloading the app #3098
- [x] Upgrade to webpack 5 #3100
- [ ] further reduce the size of the main bundle #3102
- [ ] ensure that the main bundle remains small #3101

**Comment by jasonLaster** [comment]
It would be nice to re-evaluate NextJS and see if we can take advantage of some of the advantages the framework offers

https://nextjs.org/

Here's where I think it will help:

* vercel handles resources and caching
* Routing for the library, devtools, settings etc...
* faster navigations
* static and server side rendering approaches which can be useful for initial paints
* preview branches in vercel
* faster vercel deploys

**Comment by jasonLaster** [comment]
By the way, i looked into teaching vercel to use our webpack setup and got pretty close

* vercel now has a devtools project
* the build completes but is missing images
* we could use webpack to copy images and the index.html file into dist to simplify it
* we should teach auth0 to trust vercel

**Comment by jasonLaster** [comment]
just looked into switching to next and found a couple of things

https://github.com/RecordReplay/devtools/compare/master...jasonLaster:vercel2?expand=1

* server side rendering should be disabled because we have several window dependencies
* CSS loading will have to be moved to the top level or we'll need to switch to css modules
* next is generally pretty flexible and the compiles are fast
