### ISSUE TITLE
July Onboarding Refresh

### ISSUE THREAD

**Issue by jonbell-lot23** [RecordReplay/devtools#3108]
Here's a link to the Figma file: https://www.figma.com/file/SSr1ljyzF0lCXTL7BX1Whh/Replay-Design-Doc?node-id=5210%3A12083

**Here are the steps people will walk through, in order:**

1. Big bold welcome screen
2. Download links
3. Nicer Google signin
4. Create your first Replay screen
5. Glitch demo with circles?
6. Console.logs in dev

From a priority standpoint, let's do it like this:

- [x] [New onboarding demo with great console logs](https://github.com/RecordReplay/devtools/issues/3109)
- [x] [New welcome and download screens (for people just invited)](https://github.com/RecordReplay/devtools/issues/3046)
- [x] [Nicer Google login](https://github.com/RecordReplay/devtools/issues/3111)

**Comment by jonbell-lot23** [comment]
Here's the high level view of the proposed flow:
![image](https://user-images.githubusercontent.com/9154902/126236924-aad177cd-e68b-4a7f-a2ea-7e561396eef7.png)

I'll split these into distinct issues next

**Comment by jonbell-lot23** [comment]
Shipped!
