### ISSUE TITLE
New Onboarding UX: Bugbash

### ISSUE THREAD

**Issue by jonbell-lot23** [RecordReplay/devtools#3168]
Once we get these items figured out, we can send out a batch of 100 beta list invites!

- [x] The demo site needs a title
- [x] The demo site console.logs refer to "line X." It should be "line 31"
- [x] [Library should have a white edit button, not blue](https://github.com/RecordReplay/devtools/issues/3150)
- [x] [Blue flash when loading a Replay](https://github.com/RecordReplay/devtools/issues/3063)
- [x] Disabled button should be gray in welcome screen
- [x] Spinner text should say "Hang tight!"
- [ ] [Nicer Google Login](https://github.com/RecordReplay/devtools/issues/3111)
- [x] [Breakpoint comments should never look disabled](https://github.com/RecordReplay/devtools/issues/3112) <-- this needs to be discussed with the team. See discussion in the ticket
