### ISSUE TITLE
ReactDevTools V2

### ISSUE THREAD

**Issue by hbenl** [RecordReplay/devtools#3469]
- [x] highlight and pick components #3466
- [ ] jump to the corresponding DOM node #3467
- [ ] jump to the component's source #3468

**Comment by jasonLaster** [comment]
Closing in favor of discussing / tracking in this Notion project
https://www.notion.so/replayio/React-DevTools-58c1b46fce3a4a418191604eda3cede4
