### ISSUE TITLE
Jon's big list of design tasks

### ISSUE THREAD

**Issue by jonbell-lot23** [RecordReplay/devtools#3678]
- [x] Library un-zigzagification with Jaril
- [x] [Library should show a free trial badge](https://github.com/RecordReplay/devtools/issues/3651)
- [x] [Improve Replay platform warnings](https://github.com/RecordReplay/gecko-dev/issues/523)
- [x] [Add content to login page to better direct users](https://github.com/RecordReplay/devtools/issues/3670)
- [x] #3680
- [x] #3679
- [ ] #3694
- [ ] #3681
- [ ] #3693

**Comment by jonbell-lot23** [comment]
Closing this ticket in favour of the smaller ones I just carved off
