### ISSUE TITLE
Andarist Feedback

### ISSUE THREAD

**Issue by jonbell-lot23** [RecordReplay/devtools#3684]
Sometimes things take time to resolve (up to a couple of seconds) - I know optimizing this can be super challenging and it's not that big of a problem to me. However, visual feedback for all of those things would be much appreciated because I'm getting lost as a user and I don't know if something doesn't work, if it crashed or if i'm just waiting for a response.

Notable areas for improvement:

**Perceived Performance**

- [ ] **Console Evaluations** evaluating things in the console -> I don't see any progress/loading indicator there and if it takes too much time then I just feel like it doesn't work and it got stuck but surprisingly sometimes I get a response back in the end https://github.com/RecordReplay/devtools/issues/3698

- [ ] **Pausing** stepping over (and possibly other step types as well) -> when stepping over the currently highlighted code line stops being highlighted (and I think the call stack, scope info etc on the left gets removed as well but not 100% sure) and the next line don't get immediately highlighted. So, for a bit, I can see the source panel in the "unpaused" state - I've thought that stepping just crashed and that I will have to try again or refresh a replay, but... it resolved after few secs https://github.com/RecordReplay/devtools/issues/3697

- [ ] **Inline Previews** hovering over identifiers -> u wait for the information from the backend until u show the tooltip~ but that is also too slow and I just often give up because I assume that it just won't resolve and something is broken, which often is not true. Showing the tooltip immediately, with a loader inside, could help here. https://github.com/RecordReplay/devtools/issues/3696

- [ ] **Gutter Tooltip** hover over a line number in the "gutter" I'm either seeing "Indexing" or "..." before the number of hits is returned to me, I would probably prefer this to be consistent or for "..." to be replaced with some descriptive text.  Jon: Having two states is fine, but "..." isn't descriptive, especially when it sits there for a while and seems broken. https://github.com/RecordReplay/devtools/issues/3702

### UX

- [ ] **Perf notifications** yep, similar care could be applied to errors as well here - quite frankly I don't recall seeing any error message within Replay, apart from the evaluation errors and a screen dedicated for a crash. not every error leads to it, nor every error should lead to it. It would be nice for less important errors to be communicated clearly as well if anything - it's a signal for me that something has completed, so i dont have to stare at the screen, hoping for some background call to finish  https://github.com/RecordReplay/devtools/issues/3694

- [ ] **Refresh loses context** when i'm kicked out of the session (due to inactivity) and I refresh - I see, for a moment, a spot I was looking at before I was kicked out and then I'm being taken to the breakpoint I have actually started from, so I lost the context a little bit and have to locate where I was before being kicked out and also, even though I'm stopped on a line, I'm being in the Comments tab (in the panel on the left), where, really, Pause information makes much more sense as a default in such a situation, and even more so because I was there before I got kicked out. (In other words, we need to maintain the last thing you were looking at) https://github.com/RecordReplay/devtools/issues/3701

- **Console History** and I can't use arrows in the console to look through the "latest expressions". I've types out context.properties, that got evaluated, but I was at a wrong iteration of the loop. So I've continued to the correct one, pressed arrow up in the console and I was expected context.properties to be put in the console so I could only press Enter to evaluate it https://github.com/RecordReplay/devtools/issues/3695

- **Continue to here** also - can't find "continue to here" anywhere (In the debugger you can often choose "continue to here" option from the context menu, when you click on the code line, which basically makes the debugger to "run" until it hits that line. If I have a long function and I want to get to its nth line it's often a handy "command" because it saves me time. I don't have to step over lines N times.  https://github.com/RecordReplay/devtools/issues/3702

**Comment by jonbell-lot23** [comment]
Jason is making changes right now so I'm going to put my notes down here and modify them as we de-dupe

Console needs a better loading indicator
Stepping over needs a better loading indicator
Hovering over identifiers needs a better loading indicator
Breakpoint hover needs a better loading indicator
Errors need to be communicated better
After being kicked out of a session, the refresh should take you back to the same place
Console should support up and down arrows for history
Feature request: "continue to here"

**Comment by jonbell-lot23** [comment]
Now that each of these have their own ticket, I'm going to close this one
