### ISSUE TITLE
Improve full text search

### ISSUE THREAD

**Issue by jasonLaster** [RecordReplay/devtools#3852]
### Discussed in https://github.com/RecordReplay/devtools/discussions/3766

<div type='discussions-op-text'>

<sup>Originally posted by **jasonLaster** September 25, 2021</sup>
**Description:**

Full project search is currently pretty slow because we have to first fetch all the files and then search them in a worker. We could speed this up by doing the search on the backend with ripgrep and streaming the results.</div>

### Todos
- [x] #4427
- [x] #4428
- [x] #4429
- [x] #4430
- [x] https://github.com/RecordReplay/devtools/issues/4573
- [x] https://github.com/RecordReplay/devtools/issues/4585
- [x] https://github.com/RecordReplay/devtools/issues/4597
- [x] Remember search history
- [x] select result with arrow keys
- [x] left arrow key should collapse section
- [x] down arrow from input should go to results
- [x] https://github.com/RecordReplay/backend/issues/3668
- [ ] Add include / exclude path query parameter

### Nice to have
- [ ] option to search node_modules
- [ ] matchCase, regex, word break

**Comment by jasonLaster** [comment]
Small, mostly marketing change. I think we should refer to this as Full Text Search
