### ISSUE TITLE
Elements Panel - Improve markup tree rendering

### ISSUE THREAD

**Issue by jasonLaster** [RecordReplay/devtools#4563]
**Description**
The markup tree should look similar to Firefox and Chrome

**Todos**
- [ ] the expand toggle should be white when selected
- [ ] the node wrapping should be consistent with other devtools. ([loom](https://www.loom.com/share/9dbabd46435248a3af1914f9a75b9056))
- [ ] the selected background should be full-width

<img width="1148" alt="Frame 2 (1)" src="https://user-images.githubusercontent.com/254562/142460870-f7b9a603-7ce4-49c0-9e85-db1b007d909e.png">
<img width="1072" alt="Frame 1" src="https://user-images.githubusercontent.com/254562/142460879-da9f18af-ceff-4baa-9c36-739bbb849fc1.png">
