### ISSUE TITLE
Focus Mode 1.1

### ISSUE THREAD

**Issue by jonbell-lot23** [RecordReplay/devtools#6571]
**Background**

Focus Mode is missing some important stuff. [Here's a loom](https://www.loom.com/share/c84c600cb7684fc7bf65d8c2fd2d07ee) proposing some good improvements.

[Here's the original design ticket](https://github.com/RecordReplay/design/issues/28)
[Figma link](https://www.figma.com/file/mAotNZRv6M5X0zHIFKPzFY/?node-id=11491%3A103519)
[Discord thread](https://discord.com/channels/779097926135054346/968316622475513976)

**Details**

* [x] We default the timeline to a smaller window, rather than requiring it – #6685
* [x] It's possible to drag the window right and left by clicking in the middle of it – #6685
* [x] We have save, cancel, and discard now – #6685
* [x] We have a new precision editor in the bottom-right corner – #6685
* [ ] We can focus via context menus in the call stack, console logs ([Pending design ticket here](https://github.com/RecordReplay/devtools/issues/6571))

**Comment by bvaughn** [comment]
Just watched through the Loom. Looks like a great set of changes.

**Comment by jonbell-lot23** [comment]
Adding notes to discuss later:

* Zoom with scroll wheel?
* Click to drag window range

**Comment by bvaughn** [comment]
PR #6685 just landed with most of the 1.1 features!

No context menu features yet (since they're still pending). Play with it and let's talk about tweaks?

**Comment by bvaughn** [comment]
@jonbell-lot23 In the issue description, where it says "Pending design ticket here", it's just a link back to this issue 😄
